image: python:3.5

before_script:
  - apt-get update -qy
  - apt-get install -y libdbus-1-dev libparted-dev
  - pip install -r requirements.txt

build:
  script:
    - python setup.py build
  when: on_success
