image: python:3.5
stages:
  - build
  - test

before_script:
  - apt-get update -qy
  - apt-get install -y libsasl2-dev libldap2-dev libssl-dev libdbus-1-dev libdbus-glib-1-dev libparted-dev
  - pip install -r requirements.txt

build:
  script:
    - python setup.py build
  when: on_success

test:
  script:
    - python setup.py test
  when: on_success
