image: python:3.5

before_script:
  - apt-get update -qy
  - apt-get install -y libcryptsetup-dev python3-gi libsasl2-dev libldap2-dev libssl-dev libdbus-1-dev libdbus-glib-1-dev libparted-dev
  - wget http://http.us.debian.org/debian/pool/main/p/pygobject/python3-gi_3.22.0-1_amd64.deb
  - dpkg -i python3-gi_3.22.0-1_amd64.deb

test:
  script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - ln -s /usr/lib/python3/dist-packages/gi venv/lib/python3.5/site-packages/
    - python setup.py test
  when: on_success
