image: python:3.5

before_script:
  - apt-get update -qy
  - apt-get install -y libcryptsetup-dev python3-gi python3-gobject libsasl2-dev libldap2-dev libssl-dev libdbus-1-dev libdbus-glib-1-dev libparted-dev

test:
  script:
    - python setup.py test
  when: on_success
